application: followize
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: common/appenginepatch/main.py
